#ifndef _TOUBI_H_
#define _TOUBI_H

int key();
void hanzi(char *str, int x,int y,int d,int ROW,int COL,int color) ;
void toubijiemian();
void huatoubizhengtijiemian();
void huatoubiji();
void huachubiji();
void huaqianbi10();
void huaqianbi5();
void huaqianbi1();
int  toubi10(int sum,int touru);
int  toubi5(int sum,int touru);
int  toubi1(int sum,int touru);
int  toubi(int sum);
int  toubijiemian(float money1);



#endif